"""
PreToolUse hook -- global, fires on Edit/Write/NotebookEdit calls whose target path
falls under a generated/vendored/lockfile pattern (node_modules, dist, build, vendor,
.venv, __pycache__, target, .next, generated/, *.lock, etc.).

Scope, by design: a single, purely path-based deterministic check. There is
essentially never a legitimate reason for an agent to hand-edit vendored or
generated content directly -- these are regenerated by their own tool (npm
install, a build command, a code generator), and hand-editing them either gets
silently overwritten on the next regeneration or corrupts a file whose exact
format another tool depends on.

Decision policy: deny, with a reason naming the matched pattern and what to do
instead (edit the source the generated file comes from; use the package
manager for a lockfile). No `ask` -- this is a mechanical invariant, not a
judgment call a human needs to weigh in on.
"""

import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))
from _hooklib import load_payload as _load_payload  # noqa: E402

import json
import re


FORBIDDEN_PATH_PATTERNS = [
    (re.compile(r"(^|[/\\])node_modules([/\\]|$)"), "node_modules (npm/yarn/pnpm-managed)"),
    (re.compile(r"(^|[/\\])(dist|build)([/\\]|$)"), "a build output directory"),
    (re.compile(r"(^|[/\\])vendor([/\\]|$)"), "a vendored-dependency directory"),
    (re.compile(r"(^|[/\\])(\.venv|venv)([/\\]|$)"), "a Python virtual environment"),
    (re.compile(r"(^|[/\\])__pycache__([/\\]|$)"), "a Python bytecode cache directory"),
    (re.compile(r"(^|[/\\])target([/\\]|$)"), "a Rust/Java/Maven/Gradle build output directory"),
    (re.compile(r"(^|[/\\])\.next([/\\]|$)"), "a Next.js build output directory"),
    (re.compile(r"(^|[/\\])generated([/\\]|$)"), "a directory named 'generated'"),
    (re.compile(r"(^|[/\\])\.git([/\\]|$)"), "git's own internal directory"),
    (re.compile(r"[/\\]?package-lock\.json$"), "a package-manager lockfile (npm)"),
    (re.compile(r"[/\\]?yarn\.lock$"), "a package-manager lockfile (yarn)"),
    (re.compile(r"[/\\]?pnpm-lock\.yaml$"), "a package-manager lockfile (pnpm)"),
    (re.compile(r"[/\\]?poetry\.lock$"), "a package-manager lockfile (poetry)"),
    (re.compile(r"[/\\]?Pipfile\.lock$"), "a package-manager lockfile (pipenv)"),
    (re.compile(r"[/\\]?Cargo\.lock$"), "a package-manager lockfile (cargo)"),
    (re.compile(r"[/\\]?go\.sum$"), "a package-manager lockfile (go modules)"),
    (re.compile(r"[/\\]?Gemfile\.lock$"), "a package-manager lockfile (bundler)"),
    (re.compile(r"[/\\]?composer\.lock$"), "a package-manager lockfile (composer)"),
]

EDIT_TOOL_NAMES = {"Edit", "Write", "NotebookEdit"}


def matched_pattern(path):
    for pattern, label in FORBIDDEN_PATH_PATTERNS:
        if pattern.search(path):
            return label
    return None


def deny(reason):
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))


def main():
    try:
        data = _load_payload()
    except Exception:
        return

    tool_name = data.get("tool_name")
    if tool_name not in EDIT_TOOL_NAMES:
        return

    tool_input = data.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not path:
        return

    label = matched_pattern(path)
    if label is None:
        return

    deny(
        f"forbidden-change-guard: '{path}' is under {label} -- these are "
        f"regenerated by their own tool, not hand-edited. Edit the source this "
        f"file is generated from, or use the relevant package manager/build "
        f"command instead."
    )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        pass
